// <auto-generated />
namespace HomeDepotWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Link : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Link));
        
        string IMigrationMetadata.Id
        {
            get { return "202003310959495_Link"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
